version: "3"
services:
     mongodb:
          networks:
               - mired
          image: mongo:5.0.8
          container_name: "mongodb"
          environment:
               - DATABASE_NAME=teamcamp
          volumes:
               - mongodata:/data/db
          command: mongod
     mirestaurante:
          networks:
               - mired
          build: .
          environment:
               - MONGO_DATABASE_NAME=teamcamp
               - MONGO_HOST=mongodb
          ports:
               - "4040:3099"
          depends_on:
               - mongodb
          volumes:
               - ${PWD}/../statics:/app/public/images
          restart: always
volumes:
     mongodata:
networks:
     mired: 